#!/bin/bash
set -ex

copy_builtin_skills() {
        local dest="$1"
        rm -rf "$dest/skills"
        cp -R ../common/src/base/skills "$dest/skills"
}

copy_builtin_agents() {
        local dest="$1"
        rm -rf "$dest/agents"
        cp -R ../common/src/base/agents "$dest/agents"
}

# we upload the released file to npm and run using node,
# we use bun to utilize local dev,
# so add this dispatcher if run bun locally
build_js() {
        BUN_VERSION=$(bun --version)
        REQUIRED_VERSION="1.2.15"

        if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$BUN_VERSION" | sort -V | tail -n 1)" != "$REQUIRED_VERSION" ]; then
                echo "Error: The current bun version ($BUN_VERSION) has an issue building the node target for Pochi." >&2
                echo "Please use a version up to 1.2.15." >&2
                exit 1
        fi

        bun build src/cli.ts \
                --external lightningcss \
                --target node \
                --outdir ./dist \
                --asset-naming="[name].[ext]" \
                "$@"

        # since we added bun shebang in cli.ts use bun to run pochi locally
        # bun build will always add bun shebang for cli.js,
        # so we have to replace it manually.
        sed -i.bak '1s|^.*$|#!/usr/bin/env node|' ./dist/cli.js
        rm -f ./dist/cli.js.bak

        copy_builtin_skills ./dist
        copy_builtin_agents ./dist
}

restore_embeds_stub() {
        cat <<'STUB' > ./src/lib/builtin-embeds.generated.ts
// This file is overwritten by `scripts/build-cli.sh` at `bun build --compile`
// time with static `import "..." with { type: "file" }` statements for every
// built-in skill / agent markdown file. The bundler picks them up via the
// transitive import below and embeds them into the binary, so
// `Bun.embeddedFiles` is populated at runtime.
//
// In dev / `--target node` builds this file stays empty and the loaders in
// `builtin-skills-dir.ts` / `builtin-agents-dir.ts` fall back to the
// on-disk resolution paths.
export {};
STUB
}

# Embed the built-in skill / agent markdown directly into the standalone
# binary. Bun 1.3.4 (pinned via `packageManager` in `package.json`) has a
# regression where passing multiple entry points to `bun build --compile`
# produces a binary whose main entry never executes — so instead of passing
# every `.md` as an entry point, we copy the markdown into a flat staging
# dir under `src/lib/` and generate a TS module full of
# `import "..." with { type: "file" }` statements that the bundler can
# follow from `cli.ts` -> `builtin-bundle.ts` -> `builtin-embeds.generated`.
# At runtime `Bun.embeddedFiles` yields one blob per file, and
# `classifyBlob` in `builtin-bundle.ts` decodes the `<kind>__<rel>` flat
# name back into the original `<kind>/<rel>` layout before materializing.
build_exe() {
        local staging embed_file
        staging="./src/lib/.builtin-staging"
        embed_file="./src/lib/builtin-embeds.generated.ts"

        rm -rf "$staging"
        mkdir -p "$staging"

        {
                printf '// Auto-generated by scripts/build-cli.sh. Do not edit.\n'
                while IFS= read -r f; do
                        local rel encoded
                        rel=${f#../common/src/base/}
                        encoded=${rel//\//__}
                        cp "$f" "$staging/$encoded"
                        printf 'import "./.builtin-staging/%s" with { type: "file" };\n' "$encoded"
                done < <(find ../common/src/base/skills ../common/src/base/agents \
                        -type f -name "*.md")
        } > "$embed_file"

        local status=0
        bun build src/cli.ts \
                --banner='import * as undici from "undici";' \
                --loader .md:file \
                --external lightningcss \
                --compile \
                --outfile ./dist/pochi \
                "$@" || status=$?

        rm -rf "$staging"
        restore_embeds_stub

        return "$status"
}

if [[ ${TARGET:-""} == "node" ]]; then
        build_js "$@"
else
        build_exe "$@"
fi
