import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const REFERENCE_DIR = join(
  import.meta.dirname,
  "..",
  "src/base/agents/guide/reference"
);

const URLS = {
  docs: "https://docs.getpochi.com/llms.txt",
  schema: "https://getpochi.com/config.schema.json",
} as const;

async function fetchText(url: string): Promise<string> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(
      `Failed to fetch ${url}: ${response.status} ${response.statusText}`
    );
  }
  return response.text();
}

async function main() {
  console.log("Fetching guide references...");

  mkdirSync(REFERENCE_DIR, { recursive: true });

  // Fetch docs (already markdown)
  console.log(`  Fetching ${URLS.docs}...`);
  const docs = await fetchText(URLS.docs);
  console.log(`  Fetching ${URLS.schema}...`);
  const schemaJson = await fetchText(URLS.schema);

  // Generate llms-txt content
  const llmsTxtContent = `// Auto-generated by scripts/fetch-guide-references.ts
// Do not edit manually

export const llmsTxt = ${JSON.stringify(docs)};
`;

  // Generate config-schema content (markdown with full JSON embedded)
  const configSchemaMarkdown = `## Configuration Schema

\`~/.pochi/config.jsonc\` uses JSONC format (JSON with comments).

\`\`\`json
${JSON.stringify(JSON.parse(schemaJson), null, 2)}
\`\`\`
`;
  const configSchemaContent = `// Auto-generated by scripts/fetch-guide-references.ts
// Do not edit manually

export const configSchema = ${JSON.stringify(configSchemaMarkdown)};
`;

  writeFileSync(join(REFERENCE_DIR, "llms-txt.ts"), llmsTxtContent, "utf-8");
  console.log(`  Saved to ${join(REFERENCE_DIR, "llms-txt.ts")}`);

  writeFileSync(join(REFERENCE_DIR, "config-schema.ts"), configSchemaContent, "utf-8");
  console.log(`  Saved to ${join(REFERENCE_DIR, "config-schema.ts")}`);

  // Clean up old files
  const { unlinkSync } = await import("node:fs");
  for (const file of ["docs.ts", "schema.ts", "docs.md", "schema.md"]) {
    try { unlinkSync(join(REFERENCE_DIR, file)); } catch {}
  }

  console.log("Done!");
}

main().catch((error) => {
  console.error("Error:", error);
  process.exit(1);
});
