name: ci

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

  # If this is enabled it will cancel current running and start latest
  cancel-in-progress: true

jobs:
  pre-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: POCHI_REMOTE_ENV=1 bun pre-push
