name: Release Pochi Cli Binary

on:
  workflow_dispatch:
  push:
    tags:
      - "cli@*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: cd packages/cli && bun run build:all && ls -R dist

      - name: Extract version and determine release type
        id: release_info
        run: |
          # Extract version number from tag (remove 'cli@' prefix)
          version=$(echo ${{ github.ref_name }} | sed 's/cli@//')
          echo "version_number=$version" >> $GITHUB_OUTPUT

          # Check if this is a pre-release (contains -alpha, -beta, or -rc)
          if echo "$version" | grep -q -e '-alpha\.' -e '-beta\.' -e '-rc\.' ; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
            echo "This is a pre-release version: $version"
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
            echo "This is a stable release version: $version"
          fi

      - name: Release Versioned
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/cli@')
        with:
          allowUpdates: true
          prerelease: ${{ steps.release_info.outputs.is_prerelease }}
          artifacts: "packages/cli/dist/*"
          name: pochi-cli@${{ steps.release_info.outputs.version_number }}
