name: Release Pochi NPM package

on:
  workflow_dispatch:
  push:
    tags:
      - "cli@*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      # bun 1.2.16 introduce a issue while building javascript target,
      # use bun version to 1.2.15 to build npm packages
      # ref: https://github.com/oven-sh/bun/pull/20265/files#diff-392a43b0ef87ff5dc0d4ab84fdc95b517eb68118e12fa2c8b55915a4155eaae1
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.15
      - run: bun install

      - name: Extract version and determine release type
        id: release_info
        run: |
          # Extract version number from tag (remove 'cli@' prefix)
          version=$(echo ${{ github.ref_name }} | sed 's/cli@//')
          echo "version_number=$version" >> $GITHUB_OUTPUT

          # Check if this is a pre-release (contains -alpha, -beta, or -rc)
          if echo "$version" | grep -q -e '-alpha\.' -e '-beta\.' -e '-rc\.' ; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
            echo "This is a pre-release version: $version"
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
            echo "This is a stable release version: $version"
          fi

      - name: Release NPM
        if: startsWith(github.ref, 'refs/tags/cli@')
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
          POCHI_CLI_NPM_NAME: ${{ vars.POCHI_CLI_NPM_NAME }}
        run: |
          cd packages/cli

          TARGET=node ./scripts/build-cli.sh

          # for test the CI release
          if [ -n "$POCHI_CLI_NPM_NAME" ]; then
            sed -i.bak "s|\"name\": .*|\"name\": \"$POCHI_CLI_NPM_NAME\",|" package.json
          fi

          IS_PRERELEASE=${{ steps.release_info.outputs.is_prerelease }}

          # we use cli.ts for local dev, and dist/cli.js for npm package
          # so we have to replace the bin path in package.json here
          sed -i.bak 's|"pochi": "src/cli.ts"|"pochi": "dist/cli.js"|' package.json
          rm -f package.json.bak
          bun publish --access public ${IS_PRERELEASE:+"--tag beta"}
